#!/usr/bin/env bash

device=$(xinput list | grep 'Synaptics TouchPad' | awk -F= '{print $2}' | awk '{print $1}')
state=$(xinput list-props "$device" | grep "Device Enabled" | grep -o "[01]$")

if [ $state == '1' ];then
  xinput --disable "$device"
else
  xinput --enable "$device"
fi
