#!/usr/bin/env bash

# we only care about controlling the active sink volume
SINK_ID=$(pactl list sinks short | awk '/RUNNING/ {print $1}')

[ ! -z $1 ] && case "$1" in
    volume_up)
        pactl set-sink-volume $SINK_ID +5%
        notify-send "Volume +5%"
        ;;
    volume_down)
        pactl set-sink-volume $SINK_ID -5%
        notify-send "Volume -5%"
        ;;
    volume_mute)
        pactl set-sink-mute $SINK_ID toggle
        notify-send "Active Sink Mute Toggled"
        ;;
esac
