#!/usr/bin/env bash

HOSTNAME=$(cat /etc/hostname)

case $HOSTNAME in
    pocoyo)
        SINK_ID=$(pactl list sinks short | grep -i 'bluez' | awk '{print $1}')
        ;;
    pato)
        SINK_ID=$(pactl list sinks short | grep -i 'alsa_output.pci-0000_00_1f' | awk '{print $1}')
        ;;
    *)
        i3-msg "Unknown Host: Set Sink ID manually"
        exit 1
        ;;
esac

[ ! -z $1 ] && case "$1" in
    volume_up)
        pactl set-sink-volume $SINK_ID +5%
        ;;
    volume_down)
        pactl set-sink-volume $SINK_ID -5%
        ;;
    volume_mute)
        pactl set-sink-mute $SINK_ID toggle
        ;;
esac
